#Настройки частоты звуков иллюгеров
#Минимальный кулдаун + случайная добавка (в тиках, 20 тиков = 1 секунда)
[cooldowns]
	#Пассивное состояние: минимальное время между звуками
	# Default: 30
	# Range: > 0
	passive_min = 30
	#Пассивное состояние: максимальная случайная добавка (nextInt)
	# Default: 60
	# Range: > 0
	passive_random = 60
	#Боевое состояние: минимальное время между звуками
	# Default: 40
	# Range: > 0
	combat_min = 40
	#Боевое состояние: максимальная случайная добавка (nextInt)
	# Default: 60
	# Range: > 0
	combat_random = 60
	#Обнаружение: минимальное время между звуками
	# Default: 100
	# Range: > 0
	spotted_min = 100
	#Обнаружение: максимальная случайная добавка (nextInt)
	# Default: 40
	# Range: > 0
	spotted_random = 40
	#Ранение: минимальное время между звуками
	# Default: 20
	# Range: > 0
	hurt_min = 20
	#Ранение: максимальная случайная добавка (nextInt)
	# Default: 20
	# Range: > 0
	hurt_random = 20
	#Победа: минимальное время между звуками
	# Default: 40
	# Range: > 0
	victory_min = 40
	#Победа: максимальная случайная добавка (nextInt)
	# Default: 20
	# Range: > 0
	victory_random = 20
